Fix python-dev dependency
When building the image, I get this error:

```
ERROR: unsatisfiable constraints:
  python-dev (missing):
    required by: world[python-dev]
```

To fix, I updated the package from `python-dev` to `python3-dev`.